// inspired by http://jasonwatmore.com/post/2017/09/16/react-redux-user-registration-and-login-tutorial-example

// just some constants for userActions
export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT',

    LOCK_REQUEST: 'USERS_LOCK_REQUEST',
    LOCK_SUCCESS: 'USERS_LOCK_SUCCESS',
    LOCK_FAILURE: 'USERS_LOCK_FAILURE',

    UNLOCK_REQUEST: 'USERS_UNLOCK_REQUEST',
    UNLOCK_SUCCESS: 'USERS_UNLOCK_SUCCESS',
    UNLOCK_FAILURE: 'USERS_UNLOCK_FAILURE',

    GETRES_REQUEST: 'USER_GET_RESERVATION_REQUEST',
    GETRES_SUCCESS: 'USER_GET_RESERVATION_SUCCESS',
    GETRES_FAILURE: 'USER_GET_RESERVATION_FAILURE',

}